toml
[versions]
agp = "8.13.2"
# ... other versions
ksp = "2.0.21-1.0.27" // Add this line

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" } // Add this line
